### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by BrownKyle** [djnugent/VisNav#1]
I'm trying to test you simulator, in vagrant. After following your instructions I am unable to run api start PrecisionLand.py it gets an error importing the files from the Common folder.

```
api start PrecisionLand.py
GUIDED> Exception in APIThread-4: No module named Common
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/droneapi/module/api.py", line 325, in run
    self.fn()
  File "/usr/local/lib/python2.7/dist-packages/droneapi/module/api.py", line 605, in <lambda>
    APIThread(self, lambda: execfile(args[1], g), args[1])
  File "PrecisionLand.py", line 9, in <module>
    from Common import VN_config
ImportError: No module named Common
```

**Comment by djnugent** [comment]
This is problem with your PATH variable. I just updated the readme.md with the appropriate export statements. Try those and report back

**Comment by BrownKyle** [comment]
I'm still getting the same error, would I have to make these available to /ardupilot/ArduCopter as that is where they are run from and not /home/ ?

**Comment by djnugent** [comment]
run `echo $PATH` and `echo $PYTHONPATH` and let me know what you get

**Comment by BrownKyle** [comment]
Hey,

I get this:
vagrant@vagrant-ubuntu-trusty-32:~$ echo $PATH
/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/src/jsbsim/src:/home/vagrant/src/ardupilot/Tools/autotest:/home/vagrant/ardupilot/Tools/autotest:/home/vagrant/visnav:/home/vagrant/visnav/Common:/home/vagrant/visnav/PrecisionLand_lib

vagrant@vagrant-ubuntu-trusty-32:~$ echo $PYTHONPATH
:/home/vagrant/visnav/PrecisionLand_lib

When I run those commands from /home/vagrant/ and the same reply when I run
it from /ardupilot/ArduCopter/ which seems to suggest it should find the
files.

Regards
Kyle

**Comment by djnugent** [comment]
Your PYHONPATH does not match the export statements in the README. Make them match and try again. I have also never run my code on vagrant so I am not sure how it will behave.

**Comment by BrownKyle** [comment]
Hey,

I can add either VisNav/ and VisNav/common through pythonpath or
VisNav/precisisonland_lib. Adding all three only returns precisionland_lib.

Regards
Kyle

**Comment by djnugent** [comment]
That sounds like a linux issue. I am not sure why that is happening.

**Comment by adrianhsm** [comment]
should export PYTHONPATH=$PYHTONPATH:$HOME/visnav/PrecisionLand_lib be changed to 
export PYTHONPATH=$PYTHONPATH:$HOME/visnav/PrecisionLand_lib,that is PYHTONPATH to PYTHONPATH

**Comment by djnugent** [comment]
@adrianhsm Good eye! I will put that in my next commit. Thanks
